spring:
    profiles:
        include:
            - client
        active: local

resilience4j:
    circuitbreaker:
        instances:
            testClient:
                ringBufferSizeInClosedState: 10
                ringBufferSizeInHalfOpenState: 30
                waitDurationInOpenState: 10000ms
                failureRateThreshold: 20
                registerHealthIndicator: false

